---
- hosts: master
  remote_user: root


  tasks:
    - name: install kubernetes on master node
      yum:
        name: kubernetes
        state: present
    - name: install etcd  on master node
      yum:
        name: etcd
        state: present

