---
- hosts: master
  remote_user: root
  vars:
    kube_port: 8080
    kube_master: 127.0.0.1

  tasks:
    #kubernetes tambien debe ser instalado en los nodos
    - name: install kubernetes on master node
      yum:
        name: kubernetes
        state: present
      #etcd solo va en master
    - name: install etcd  on master node
      yum:
        name: etcd
        state: present
    - template: #Crea el archivo /etc/kubernetes/config
        src: templates/kubernetes_config
        dest: /etc/kubernetes/config
#    - service:
#        name: firewalld
#        enabled: false
#        state: stopped 
#    - service:
#        name: iptables-services
#        enabled: false
#        state: stopped 
    - template: #Crea el archivo /etc/kubernetes/config
        src: templates/apiserver
        dest: /etc/kubernetes/apiserver
    - replace:
        destfile: /etc/etcd/etcd.conf
        regexp: '^ETCD_LISTEN_CLIENT_URLS=.http:\/\/.*:(.*)$'
        replace: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:\1'
        backup: yes
                             
...
